title: Web Development Documentation
description: Web Development Starter Kit for the 2025 Triton Hackathon hosted by CS Foreach @ UCSD.
theme: just-the-docs
color_scheme: light
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-deploy

deploy:
  provider: "github"
  repository: "tritonhacks/thwebdev-25"
  branch: "main"
  token: "..."

url: https://tritonhacks.github.io/thwebdev-25

back_to_top: true
back_to_top_text: "Back to top"

aux_links_new_tab: true
aux_links:
  CS Foreach: https://www.csforeach.org/


callouts:
  warning:
    title: Warning
    color: yellow
  hint:
    title: Hint
    color: grey-lt
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: grey-dk
  tip:
    title: Tip
    color: blue
  caution:
    title: Caution
    color: red
  attention:
    title: Attention
    color: purple
